Update README
Keennak/AWSConfigRules2CSV pull request #1
Opened 2020-08-21 10:43 UTC by s0353149

update README.

2020-08-24 06:49 UTC, Keennak requested changes
ありがとうございますー。ちょっと修正ポイントをコメントさせていただきましたー。

2020-08-24 06:49 UTC, Keennak commented on README.md
> +・bs4モジュール(pip install pyyaml)およびパーサ(pip install lxml)が必要です。
（）内、bs4の間違いかな。

2020-08-24 06:49 UTC, Keennak commented on README.md
> +
./いらないかも。

2020-08-25 02:25 UTC, s0353149 commented on README.md
> +
承知しました。修正して再度アップします。

2020-08-25 02:26 UTC, s0353149 commented
ご指摘修正版です。

2020-08-25 09:10 UTC, Keennak approved these changes

2020-08-25 09:11 UTC, Keennak commented
Update README by T.YT

2020-08-25 09:12 UTC, merged